ABLY_PROJECT_MAJOR_VERSION = 1
ABLY_PROJECT_MINOR_VERSION = 0
ABLY_PROJECT_PATCH_VERSION = 1

__version__ = "{}.{}.{}".format(ABLY_PROJECT_MAJOR_VERSION,
                                ABLY_PROJECT_MINOR_VERSION,
                                ABLY_PROJECT_PATCH_VERSION)
