# Generated by Django 3.1.5 on 2022-08-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userinfo_userlogin_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
