# Generated by Django 4.1 on 2022-08-18 13:20

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_delete_userlogin_remove_userinfo_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userauth',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(default=django.contrib.auth.models.AnonymousUser, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
