# Generated by Django 4.1 on 2022-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_create_at_userauth_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='verified',
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
